
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/security
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:


      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          show_sql: true
          format_sql: true
          use_sql_comments: true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
server:
  port: 8989

logging:
    level:
      me.silvernine: DEBUG

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
